name: VoteReward
main: me.adixe.votereward.VoteReward
version: 3.2.0
api-version: 1.18
authors: [Adixe]
description: Reward players for voting for the server.
libraries:
  - com.squareup.okhttp3:okhttp:4.12.0
commands:
  votereward:
    aliases:
      - vr
permissions:
  votereward.command:
    default: true
  votereward.reward:
    default: true
  votereward.check:
    default: op
  votereward.reload:
    default: op
