# __      __   _         _____                            _
# \ \    / /  | |       |  __ \                          | |
#  \ \  / /__ | |_ ___  | |__) |_____      ____ _ _ __ __| |
#   \ \/ / _ \| __/ _ \ |  _  // _ \ \ /\ / / _` | '__/ _` |
#    \  / (_) | ||  __/ | | \ \  __/\ V  V / (_| | | | (_| |
#     \/ \___/ \__\___| |_|  \_\___| \_/\_/ \__,_|_|  \__,_|
#
# Reward players for voting for the server.
#
# Source code and documentation: https://github.com/dudekm/VoteReward
#
# Spigot: Adixe
# Discord: adixepl
# GitHub: AdixePL
#
servers:
  lista-minecraft:
    address: https://lista-minecraft.pl
    uuid: 183413bc-4588-4265-8f06-346963e5d7df
    reward-commands:
      - xp add %player_name% 100
      - give %player_name% diamond
  lista-serwerow-emecz:
    address: https://lista-serwerow.emecz.pl
    uuid: 264acafc-136c-4def-a363-088587c7a405
    reward-commands: []
  minecraft-list:
    address: https://minecraft-list.info
    uuid: d6dfe480-da3a-495a-a92d-5a198a7f2f83
    reward-commands: []
